import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import Authenticator from "@/providers/Authenticator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Authenticator>
            <ChakraProvider>{children}</ChakraProvider>
          </Authenticator>
        </ReduxProvider>
      </body>
    </html>
  );
}
